[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"  # Or your preferred version

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200